create table data_type
(
    id                      bigserial primary key,
    name                    text
);

create table course_schema_part
(
    id                      bigserial primary key,
    course_id               bigint references course (id) on delete cascade,
    data_type               bigint references data_type (id) on delete cascade,
    name                    text,
    validator               boolean,
    validator_regex         text,
    validator_message       text,
    locked                  boolean,
    autogenerated           boolean,
    generation_statement    text,
    control_width           integer,
    orderr                  integer,
    required                boolean
);

create table course_student_data
(
    id                      bigserial primary key,
    account_id              bigint references account (id) on delete cascade,
    course_id               bigint references course (id) on delete cascade
);

create table course_data_part
(
    id                      bigserial primary key,
    course_data_id          bigint references course_student_data (id) on delete cascade,
    data_schema_part_id     bigint references course_schema_part (id) on delete cascade,
    data                    text
);