package com.example.servermaintenance.course.domain;

import lombok.Data;

@Data
public class SchemaPartDto {
    private String name = "";
    private boolean locked;
    private boolean validator;
    private String validatorRegex;
    private String validatorMessage;
    private boolean autogenerated;
    private String generationStatement;
    private int controlWidth = 4;
    private int order;
    private boolean required;
    private boolean open;

    private SchemaPart _schemaPartEntity;
}

